"""followers

Revision ID: 259ad9732f49
Revises: 0f3acd7ef9b2
Create Date: 2020-01-05 14:04:02.998000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259ad9732f49'
down_revision = '0f3acd7ef9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
